### ISSUE TITLE
Yale alarm no longer working since 0.86.1 update

### ISSUE THREAD

**Issue by partymike** [domwillcode/yale-smart-alarm-client#12]
getting the following error logged:

2019-01-25 08:53:47 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Error while setting up platform yale_smart_alarm
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/alarm_control_panel/yale_smart_alarm.py", line 46, in setup_platform
    client = YaleSmartAlarmClient(username, password, area_id)
  File "/usr/local/lib/python3.6/site-packages/yalesmartalarmclient/client.py", line 53, in __init__
    self._authorize()
  File "/usr/local/lib/python3.6/site-packages/yalesmartalarmclient/client.py", line 174, in _authorize
    data = response.json()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.6/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

tried a reboot but same issue

**Comment by domwillcode** [comment]
IIRC this was a Yale issue - closing as old!
