### ISSUE TITLE
socket.timeout: The read operation timed out

### ISSUE THREAD

**Issue by iamds** [domwillcode/yale-smart-alarm-client#20]
A few times a day I'm getting the following exception thrown. Any idea why?

```
May 22 14:56:00 raspberrypi python3[16690]: Traceback (most recent call last):
May 22 14:56:00 raspberrypi python3[16690]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
May 22 14:56:00 raspberrypi python3[16690]:     six.raise_from(e, None)
May 22 14:56:00 raspberrypi python3[16690]:   File "<string>", line 3, in raise_from
May 22 14:56:00 raspberrypi python3[16690]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
May 22 14:56:00 raspberrypi python3[16690]:     httplib_response = conn.getresponse()
May 22 14:56:00 raspberrypi python3[16690]:   File "/usr/lib/python3.7/http/client.py", line 1336, in getresponse
May 22 14:56:00 raspberrypi python3[16690]:     response.begin()
May 22 14:56:00 raspberrypi python3[16690]:   File "/usr/lib/python3.7/http/client.py", line 306, in begin
May 22 14:56:00 raspberrypi python3[16690]:     version, status, reason = self._read_status()
May 22 14:56:00 raspberrypi python3[16690]:   File "/usr/lib/python3.7/http/client.py", line 267, in _read_status
May 22 14:56:00 raspberrypi python3[16690]:     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
May 22 14:56:00 raspberrypi python3[16690]:   File "/usr/lib/python3.7/socket.py", line 589, in readinto
May 22 14:56:00 raspberrypi python3[16690]:     return self._sock.recv_into(b)
May 22 14:56:00 raspberrypi python3[16690]:   File "/usr/lib/python3.7/ssl.py", line 1052, in recv_into
May 22 14:56:00 raspberrypi python3[16690]:     return self.read(nbytes, buffer)
May 22 14:56:00 raspberrypi python3[16690]:   File "/usr/lib/python3.7/ssl.py", line 911, in read
May 22 14:56:00 raspberrypi python3[16690]:     return self._sslobj.read(len, buffer)
May 22 14:56:00 raspberrypi python3[16690]: socket.timeout: The read operation timed out
May 22 14:56:00 raspberrypi python3[16690]: During handling of the above exception, another exception occurred:
May 22 14:56:00 raspberrypi python3[16690]: Traceback (most recent call last):
May 22 14:56:00 raspberrypi python3[16690]:   File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
May 22 14:56:00 raspberrypi python3[16690]:     timeout=timeout
May 22 14:56:00 raspberrypi python3[16690]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
May 22 14:56:00 raspberrypi python3[16690]:     _stacktrace=sys.exc_info()[2])
May 22 14:56:00 raspberrypi python3[16690]:   File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 367, in increment
May 22 14:56:00 raspberrypi python3[16690]:     raise six.reraise(type(error), error, _stacktrace)
May 22 14:56:00 raspberrypi python3[16690]:   File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
May 22 14:56:00 raspberrypi python3[16690]:     raise value
May 22 14:56:00 raspberrypi python3[16690]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
May 22 14:56:00 raspberrypi python3[16690]:     chunked=chunked)
May 22 14:56:00 raspberrypi python3[16690]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 386, in _make_request
May 22 14:56:00 raspberrypi python3[16690]:     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
May 22 14:56:00 raspberrypi python3[16690]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
May 22 14:56:00 raspberrypi python3[16690]:     raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
May 22 14:56:00 raspberrypi python3[16690]: urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='mob.yalehomesystem.co.uk', port=443): Read timed out. (read timeout=5)
May 22 14:56:00 raspberrypi python3[16690]: During handling of the above exception, another exception occurred:
May 22 14:56:00 raspberrypi python3[16690]: Traceback (most recent call last):
May 22 14:56:00 raspberrypi python3[16690]:   File "web.py", line 573, in <module>
May 22 14:56:00 raspberrypi python3[16690]:     main()
May 22 14:56:00 raspberrypi python3[16690]:   File "web.py", line 568, in main
May 22 14:56:00 raspberrypi python3[16690]:     yale_client.run()
May 22 14:56:00 raspberrypi python3[16690]:   File "/home/pi/homeauto/venv/yale.py", line 21, in run
May 22 14:56:00 raspberrypi python3[16690]:     new_state = self.client.get_armed_status()
May 22 14:56:00 raspberrypi python3[16690]:   File "/home/pi/.local/lib/python3.7/site-packages/yalesmartalarmclient/client.py", line 89, in get_armed_status
May 22 14:56:00 raspberrypi python3[16690]:     alarm_state = self._get_authenticated(self._ENDPOINT_GET_MODE)
May 22 14:56:00 raspberrypi python3[16690]:   File "/home/pi/.local/lib/python3.7/site-packages/yalesmartalarmclient/client.py", line 124, in _get_authenticated
May 22 14:56:00 raspberrypi python3[16690]:     response = requests.get(url, headers=self.auth_headers, timeout=self._DEFAULT_REQUEST_TIMEOUT)
May 22 14:56:00 raspberrypi python3[16690]:   File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
May 22 14:56:00 raspberrypi python3[16690]:     return request('get', url, params=params, **kwargs)
May 22 14:56:00 raspberrypi python3[16690]:   File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
May 22 14:56:00 raspberrypi python3[16690]:     return session.request(method=method, url=url, **kwargs)
May 22 14:56:00 raspberrypi python3[16690]:   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
May 22 14:56:00 raspberrypi python3[16690]:     resp = self.send(prep, **send_kwargs)
May 22 14:56:00 raspberrypi python3[16690]:   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
May 22 14:56:00 raspberrypi python3[16690]:     r = adapter.send(request, **kwargs)
May 22 14:56:00 raspberrypi python3[16690]:   File "/usr/lib/python3/dist-packages/requests/adapters.py", line 529, in send
May 22 14:56:00 raspberrypi python3[16690]:     raise ReadTimeout(e, request=request)
May 22 14:56:00 raspberrypi python3[16690]: requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='mob.yalehomesystem.co.uk', port=443): Read timed out. (read timeout=5)

```

**Comment by qerim** [comment]
Same here. I've set alarm to Arm when I leave. Sometimes it works, other times it does not due to the above error. Very random.

![image](https://user-images.githubusercontent.com/3625009/87941423-0caeb180-ca93-11ea-96de-35ddec9d9548.png)
