### ISSUE TITLE
Error  invalid literal for int() with base 16

### ISSUE THREAD

**Issue by Marmoulak** [domwillcode/yale-smart-alarm-client#44]
Hej
I am receiving this error, can you help please?

Logger: homeassistant.components.lock
Source: custom_components/yale_doorman_via_smarthub/lock.py:100
Integration: Lock (documentation, issues)

Error adding entities for domain lock with platform yale_doorman_via_smarthub
Error while setting up yale_doorman_via_smarthub platform for lock
Traceback (most recent call last):
  File "/config/custom_components/yale_doorman_via_smarthub/lock.py", line 97, in icon
    door_status = int(self.coordinator.data["data"]["device_status"][self.idx]["minigw_lock_status"],16)
ValueError: invalid literal for int() with base 16: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 521, in _async_add_entity
    original_icon=entity.icon,
  File "/config/custom_components/yale_doorman_via_smarthub/lock.py", line 100, in icon
    door_status = self.old_door_status
AttributeError: 'YaleDoormanViaSmarthubLock' object has no attribute 'old_door_status'

**Comment by Marmoulak** [comment]
wrong place, sorry

**Comment by gjohansson-ST** [comment]
Was about to say that...
Why using a custom integration when most is in core?
